//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: Arena武斗场.xlsx SHEET: 每日排行奖励 KEY: id

#pragma once
#pragma pack(1)
struct ArenaRankReward
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // ID
	DWORD rank_cap; // 排名上限
	DWORD rank_floor; // 排名下限
	DWORD ticket_reward; // 文钱奖励
	DWORD gold_reward; // 金币奖励
	DWORD score_reward; // 积分奖励
	DWORD experience_reward; // 主角经验奖励
};
#pragma pack()

#if false
namespace table
{
	// Arena武斗场
	struct zArenaRankRewardEntry : public zEntry
	{
		DWORD id; // ID
		DWORD rank_cap; // 排名上限
		DWORD rank_floor; // 排名下限
		DWORD ticket_reward; // 文钱奖励
		DWORD gold_reward; // 金币奖励
		DWORD score_reward; // 积分奖励
		DWORD experience_reward; // 主角经验奖励

		virtual const char* getClassName() const { return "Arena武斗场"; }
		static const char* getFileName() { return "ArenaRankReward.tbl"; }
		void fill(const ArenaRankReward& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			this->rank_cap = base.rank_cap;
			this->rank_floor = base.rank_floor;
			this->ticket_reward = base.ticket_reward;
			this->gold_reward = base.gold_reward;
			this->score_reward = base.score_reward;
			this->experience_reward = base.experience_reward;
		}
		void reset()
		{
			this->id = 0;
			this->rank_cap = 0;
			this->rank_floor = 0;
			this->ticket_reward = 0;
			this->gold_reward = 0;
			this->score_reward = 0;
			this->experience_reward = 0;
		}
	};
	typedef zDataBM<zArenaRankRewardEntry, ArenaRankReward> ArenaRankRewardManager;
}
#endif

