//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 排行榜.xlsm SHEET: 排行榜表格 KEY: ID

#pragma once
#pragma pack(1)
struct RankDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(ID); }

	DWORD ID; // ID
	DWORD showRank; // 显示排名
	DWORD max_num; // 总共排名
	DWORD order_type; // 榜单类型
};
#pragma pack()

#if false
namespace table
{
	// 排行榜
	struct zRankDataBaseEntry : public zEntry
	{
		DWORD ID; // ID
		DWORD showRank; // 显示排名
		DWORD max_num; // 总共排名
		DWORD order_type; // 榜单类型

		virtual const char* getClassName() const { return "排行榜"; }
		static const char* getFileName() { return "RankDataBase.tbl"; }
		void fill(const RankDataBase& base)
		{
			this->id = base.getUniqueID();

			this->ID = base.ID;
			this->showRank = base.showRank;
			this->max_num = base.max_num;
			this->order_type = base.order_type;
		}
		void reset()
		{
			this->ID = 0;
			this->showRank = 0;
			this->max_num = 0;
			this->order_type = 0;
		}
	};
	typedef zDataBM<zRankDataBaseEntry, RankDataBase> RankDataBaseManager;
}
#endif

