//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: Robot.xlsx SHEET: Sheet1 KEY: id

#pragma once
#pragma pack(1)
struct RobotDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // ID
	DWORD npc_id; // NPCID
	DWORD fight_power; // 战斗力
};
#pragma pack()

#if false
namespace table
{
	// Robot
	struct zRobotDataBaseEntry : public zEntry
	{
		DWORD id; // ID
		DWORD npc_id; // NPCID
		DWORD fight_power; // 战斗力

		virtual const char* getClassName() const { return "Robot"; }
		static const char* getFileName() { return "RobotDataBase.tbl"; }
		void fill(const RobotDataBase& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			this->npc_id = base.npc_id;
			this->fight_power = base.fight_power;
		}
		void reset()
		{
			this->id = 0;
			this->npc_id = 0;
			this->fight_power = 0;
		}
	};
	typedef zDataBM<zRobotDataBaseEntry, RobotDataBase> RobotDataBaseManager;
}
#endif

