//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: Robot.xlsx SHEET: Sheet1 KEY: id

#pragma once
#pragma pack(1)
struct RobotDataBase
{
	DWORD getUniqueID() const { return usage_id_hash(id); }

	DWORD id; // ID
	DWORD level; // 等级
	char name[32]; // 名字
	DWORD job; // 职业
	DWORD model_id; // 模型ID
	DWORD life; // 生命
	DWORD pdam; // 物理攻击
	DWORD pdef; // 物理防御
	DWORD mdam; // 法术攻击
	DWORD mdaf; // 法术防御
	DWORD hit; // 命中
	DWORD hide; // 闪避
	char skill[32]; // 技能
	DWORD fight_power; // 战斗力
};
#pragma pack()

#if false
namespace table
{
	// Robot
	struct zRobotDataBaseEntry : public zEntry
	{
		DWORD id; // ID
		DWORD level; // 等级
		char name[32]; // 名字
		DWORD job; // 职业
		DWORD model_id; // 模型ID
		DWORD life; // 生命
		DWORD pdam; // 物理攻击
		DWORD pdef; // 物理防御
		DWORD mdam; // 法术攻击
		DWORD mdaf; // 法术防御
		DWORD hit; // 命中
		DWORD hide; // 闪避
		char skill[32]; // 技能
		DWORD fight_power; // 战斗力

		virtual const char* getClassName() const { return "Robot"; }
		static const char* getFileName() { return "RobotDataBase.tbl"; }
		void fill(const RobotDataBase& base)
		{
			this->id = base.getUniqueID();

			this->id = base.id;
			this->level = base.level;
			strncpy(this->name, base.name, 32);
			this->job = base.job;
			this->model_id = base.model_id;
			this->life = base.life;
			this->pdam = base.pdam;
			this->pdef = base.pdef;
			this->mdam = base.mdam;
			this->mdaf = base.mdaf;
			this->hit = base.hit;
			this->hide = base.hide;
			strncpy(this->skill, base.skill, 32);
			this->fight_power = base.fight_power;
		}
		void reset()
		{
			this->id = 0;
			this->level = 0;
			this->name[0] = '\0';
			this->job = 0;
			this->model_id = 0;
			this->life = 0;
			this->pdam = 0;
			this->pdef = 0;
			this->mdam = 0;
			this->mdaf = 0;
			this->hit = 0;
			this->hide = 0;
			this->skill[0] = '\0';
			this->fight_power = 0;
		}
	};
	typedef zDataBM<zRobotDataBaseEntry, RobotDataBase> RobotDataBaseManager;
}
#endif

