//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// FILE: 组队活动表.xlsx SHEET: 组队目标 KEY: mainID + indexID

#pragma once
#pragma pack(1)
struct TeamActivityDatabase
{
	DWORD getUniqueID() const { return usage_id_hash(mainID, indexID); }

	DWORD indexID; // 小类ID
	DWORD mainID; // 大类ID
	char mainName[32]; // 大类名称
	char indexName[32]; // 小类名称
	DWORD min; // 等级下限
	DWORD max; // 等级上限
};
#pragma pack()

#if false
namespace table
{
	// 组队活动表
	struct zTeamActivityDatabaseEntry : public zEntry
	{
		DWORD indexID; // 小类ID
		DWORD mainID; // 大类ID
		char mainName[32]; // 大类名称
		char indexName[32]; // 小类名称
		DWORD min; // 等级下限
		DWORD max; // 等级上限

		virtual const char* getClassName() const { return "组队活动表"; }
		static const char* getFileName() { return "TeamActivityDatabase.tbl"; }
		void fill(const TeamActivityDatabase& base)
		{
			this->id = base.getUniqueID();

			this->indexID = base.indexID;
			this->mainID = base.mainID;
			strncpy(this->mainName, base.mainName, 32);
			strncpy(this->indexName, base.indexName, 32);
			this->min = base.min;
			this->max = base.max;
		}
		void reset()
		{
			this->indexID = 0;
			this->mainID = 0;
			this->mainName[0] = '\0';
			this->indexName[0] = '\0';
			this->min = 0;
			this->max = 0;
		}
	};
	typedef zDataBM<zTeamActivityDatabaseEntry, TeamActivityDatabase> TeamActivityDatabaseManager;
}
#endif

